name: Build & Deploy
on:
  workflow_dispatch:
  push:
    branches: [new-website]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            cd osrsquery.com
            echo 'helloworld' > hellofile.txt
            echo 'Deployment successful to digital ocean' 
