# This is a basic workflow to help you get started with Actions

name: Publish Website
on:
  push:
    branches: [ main ]

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: FTP-Deploy-Action
      uses: airvzxf/ftp-deployment-action@latest
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        ARGS: --delete
